Repository prgrms-fe-devcourse/FEDC5_MatNam_Ducki, pull requests merged in 2024-01, with the labels that each got.

#11 [✨feat]: 하단 메뉴바 구현
  src/components/BottomNavBar/BottomNavBar.tsx
  src/components/Common/Icons/MainIcon.tsx
  src/components/Common/Icons/NotificationIcon.tsx
  src/components/Common/Icons/ProfileIcon.tsx
  src/components/Common/Icons/ReviewIcon.tsx
  src/constants/index.ts
Labels: FEAT

#20 [✨feat]: API Response 타입 정의
  src/types/payload.ts
  src/types/response.ts
Labels: FEAT

#18 [✨feat]: Input 공통 컴포넌트 추가
  package.json
  src/components/Common/HookFormInput.tsx
  src/types/input.ts
  yarn.lock
Labels: FEAT

#26 [✨feat]: Avatar 컴포넌트 추가
  src/components/Common/Avatar/Avatar.tsx
Labels: FEAT

#23 [✨feat]: ReviewCard 컴포넌트 추가
  src/components/ReviewCard/ReviewCard.tsx
Labels: FEAT

#24 [✨feat]: 전역 스타일 적용하기
  src/App.tsx
  src/assets/Fonts.css
  src/main.tsx
  src/styles/Global.ts
  src/styles/Theme.ts
  src/styles/emotion.d.ts
Labels: FEAT

#32 [✨feat]: react-query 초기 설정
  package.json
  src/App.tsx
  src/main.tsx
  yarn.lock
Labels: FEAT

#40 [✨feat]: ChannelList 컴포넌트 구현
  .gitignore
  src/components/Channel/ChannelList.tsx
  src/hooks/useGetChannel.ts
Labels: FEAT

#43 [✨feat]: Recoil 초기 설정, localStorageEffect 추가
  src/main.tsx
  src/recoil/index.ts
  src/recoil/localStorage.ts
Labels: FEAT

#34 [✨feat]: 유저 프로필 페이지 구현
  src/components/LikePosts/LikePosts.tsx
  src/components/MyPosts/MyPosts.tsx
  src/components/PostSelector/PostSelector.tsx
  src/components/ProfileImage/ProfileImage.tsx
  src/components/UserInfo/UserInfo.tsx
  src/components/UserIntroductionEditor/UserIntroductionEditor.tsx
  src/constants/profile.tsx
  src/pages/ProfilePage.tsx
  src/types/profile.ts
  yarn.lock
Labels: FEAT

#39 [✨feat]: 회원가입 UI 구현 및 API 연동
  src/App.tsx
  src/components/Common/HookFormInput.tsx
  src/components/SignUpForm/index.tsx
  src/components/SignUpForm/style.ts
  src/constants/validation.ts
  src/hooks/useAuth.ts
  src/pages/SignUpPage.tsx
  src/pages/SignupPage.tsx
  src/services/Auth/auth.ts
  src/services/axiosInstance.ts
  src/types/input.ts
  src/utils/validation.ts
Labels: FEAT

#46 [✨feat]: 인증 API 사용을 위한 테스트 계정 로그인 버튼 추가
  src/hooks/useAuth.ts
  src/pages/MainPage.tsx
  src/services/axiosInstance.ts
Labels: FEAT

#53 [🎨style]: 루트 폰트 크기 설정
  src/styles/Global.ts
Labels: STYLE

#50 [✨feat]: Modal 공통 컴포넌트 구현, 프로필 사진 변경 모달 추가
  index.html
  src/components/Common/Icons/CloseIcon.tsx
  src/components/Common/Modal/BaseModal/index.tsx
  src/components/Common/Modal/BaseModal/style.ts
  src/components/Common/Modal/ChangeImageModal/index.tsx
  src/components/Common/Modal/ChangeImageModal/style.ts
  src/components/Common/Modal/ModalComponent/index.tsx
  src/components/Common/Modal/ModalContainer/index.tsx
  src/hooks/useModal.ts
  src/recoil/modal.ts
  src/types/modal.ts
  src/utils/scroll.ts
Labels: FEAT

#55 [✨feat]: Route 구조 변경 및 ErrorBoundary, Suspense 적용
  package.json
  src/App.tsx
  src/components/Common/ErrorFallback/index.tsx
  src/pages/MainPage.tsx
  src/pages/TestPage.tsx
  src/routes/index.tsx
  src/routes/path.ts
  yarn.lock
Labels: FEAT

#49 [✨feat]: Review 등록 페이지 & 기능 구현
  src/components/Channel/ChannelList.tsx
  src/hooks/useCreatePost.ts
  src/pages/ReviewPage.tsx
  src/pages/ReviewPage/index.tsx
  src/pages/ReviewPage/style.ts
  src/services/Post/post.ts
  src/services/reviewService.ts
Labels: FEAT

#45 [✨feat]: api 연동하여 프로필 페이지 구현
  src/components/Common/Avatar/Avatar.tsx
  src/components/Common/Icons/MainIcon.tsx
  src/components/Common/Icons/NotificationIcon.tsx
  src/components/Common/Icons/ProfileIcon.tsx
  src/components/Common/Icons/ReviewIcon.tsx
  src/components/Common/ImageUpload.tsx
  src/components/LikePosts/LikePosts.tsx
  src/components/MyPosts/MyPosts.tsx
  src/components/PostSelector/PostSelector.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/components/Skeleton/index.tsx
  src/components/UserInfo/UserInfo.tsx
  src/components/UserIntroductionEditor/UserIntroductionEditor.tsx
  src/hooks/useGetProfile.ts
  src/pages/ProfilePage.tsx
  src/services/User/user.ts
Labels: FEAT

#63 [✨feat]: getElapsedTime 함수 구현
  package.json
  src/utils/getElapsedTime.ts
  yarn.lock
Labels: FEAT

#66 [🎨style]: ReviewPage 스타일링 수정
  src/components/Common/Button/Button.tsx
  src/components/Common/ImageUpload.tsx
  src/pages/ReviewPage/index.tsx
  src/pages/ReviewPage/style.ts
Labels: STYLE

#68 [✨feat]: 로그인 UI 구현 및 API 연동
  src/components/SignInForm/SignInForm.tsx
  src/components/SignInForm/style.ts
  src/pages/SignInPage/SignInPage.tsx
  src/pages/SignInPage/style.ts
  src/pages/SigninPage.tsx
  src/routes/index.tsx
Labels: FEAT

#73 [✨feat]: 게시물 작성자의 프로필 구현
  public/profileBackground.png
  src/components/ UserPosts/index.tsx
  src/components/ UserPosts/style.ts
  src/components/BottomNavBar/BottomNavBar.tsx
  src/components/PostUserProfile/index.tsx
  src/components/PostUserProfile/style.ts
  src/components/ReviewCard/ReviewCard.tsx
  src/hooks/useGetProfile.ts
  src/routes/index.tsx
Labels: FEAT

#74 [✨feat]: ReviewList 구현
  src/components/Badge/Badge.tsx
  src/components/Channel/ChannelList.tsx
  src/components/Common/Circle/index.tsx
  src/components/Common/Circle/style.ts
  src/components/ReviewCard/ReviewCard.tsx
  src/components/ReviewCard/style.ts
  src/components/ReviewCardList/index.tsx
  src/components/ReviewCardList/style.ts
  src/constants/review.ts
  src/hooks/usePost.ts
  src/pages/ReviewList.tsx
  src/pages/ReviewList/index.tsx
  src/pages/ReviewList/style.ts
Labels: FEAT

#76 [✨feat]: Post 데이터 커스터마이징
  src/pages/ReviewPage/index.tsx
  src/services/Post/post.ts
  src/types/payload.ts
  src/types/response.ts
Labels: FEAT

#80 [♻️refactor]: ReviewPage에 API 커스터마이징한 부분 적용
  src/components/Badge/Badge.tsx
  src/components/Channel/ChannelList.tsx
  src/components/Common/ImageUpload.tsx
  src/hooks/useInput.ts
  src/pages/ReviewPage/index.tsx
  src/pages/ReviewPage/style.ts
  src/utils/validation.ts
Labels: STYLE, REFACTOR

#83 [✨feat]: 카카오 지도 API를 이용한 음식점 검색 페이지 구현
  index.html
  package.json
  public/images/marker.png
  src/components/Common/Icons/PlaceIcon.tsx
  src/components/SearchBar/index.tsx
  src/components/SearchBar/style.ts
  src/components/SearchMap/PlaceList/index.tsx
  src/components/SearchMap/PlaceList/style.ts
  src/components/SearchMap/index.tsx
  src/components/SearchMap/style.ts
  src/pages/SearchMapPage/index.tsx
  src/pages/SearchMapPage/style.ts
  src/pages/SearchPage.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/types/placeMap.ts
  vite.config.ts
  yarn.lock
Labels: FEAT

#88 [✨feat]: ReviewUpdate 구현
  src/hooks/useCreatePost.ts
  src/hooks/useInput.ts
  src/hooks/usePost.ts
  src/pages/ReviewPage/index.tsx
  src/pages/ReviewUpdatePage/index.tsx
  src/pages/ReviewUpdatePage/style.ts
  src/routes/index.tsx
  src/routes/path.ts
  src/services/Post/post.ts
Labels: FEAT

#91 [✨feat]: Review 삭제 기능 구현
  src/hooks/useDeletePost.ts
Labels: FEAT

#78 [♻️refactor]: api 연동하여 프로필 페이지 리펙토링
  public/images/profileBackground.png
  src/components/LikePosts/LikePosts.tsx
  src/components/LikePosts/index.tsx
  src/components/LikePosts/style.ts
  src/components/MyPosts/index.tsx
  src/components/MyPosts/style.ts
  src/components/PostSelector/PostSelector.tsx
  src/components/PostSelector/index.tsx
  src/components/PostSelector/style.ts
  src/components/PostUserProfile/style.ts
  src/components/ProfileImage/ProfileImage.tsx
  src/components/UserInfo/UserInfo.tsx
  src/components/UserInfo/index.tsx
  src/components/UserInfo/style.ts
  src/components/UserIntroductionEditor/UserIntroductionEditor.tsx
  src/components/UserIntroductionEditor/index.tsx
  src/components/UserIntroductionEditor/style.ts
  src/components/UserPosts/index.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProfilePage/index.tsx
  src/pages/ProfilePage/style.ts
Labels: REFACTOR

#93 [♻️refactor]: ReviewDetail 수정/삭제 기능 추가, 레이아웃 수정
  src/components/Common/DropDown/index.tsx
  src/components/Common/DropDown/style.ts
  src/components/Common/Icons/MeatBallMenu.tsx
  src/components/ReviewCardList/index.tsx
  src/pages/ReviewDetailPage/index.tsx
  src/pages/ReviewDetailPage/style.ts
Labels: REFACTOR

#94 [🎨style] : PostUserProfile 스타일링 변경
  src/components/PostUserProfile/index.tsx
  src/components/PostUserProfile/style.ts
  src/components/UserPosts/style.ts
Labels: STYLE

#97 [🎨style]: detailpage 스타일링
  src/components/Common/Icons/ClockIcon.tsx
  src/components/Common/Icons/LikeIcon.tsx
  src/components/Common/Icons/ThumbsDownIcon.tsx
  src/components/Common/Icons/ThumbsUpIcon.tsx
  src/components/ReviewDetail/CommentInput.tsx
  src/components/ReviewDetail/EvaluationSection.tsx
  src/pages/ReviewDetailPage/index.tsx
  src/pages/ReviewDetailPage/style.ts
Labels: STYLE

#71 [✨feat]: 인기 검색어 컴포넌트 구현
  src/components/PopularSearch/index.tsx
  src/components/PopularSearch/style.ts
Labels: FEAT

#101 [✨feat]: User 상태 전역 관리
  src/hooks/useAuth.ts
  src/pages/MainPage.tsx
  src/recoil/user.ts
Labels: FEAT

#104 [🎨style]: 기본프로필 이미지 추가
  public/images/defaultProfileImage.png
  src/pages/ProfilePage/index.tsx
Labels: STYLE

#84 [♻️refactor]: 하단 메뉴바 리펙토링
  src/components/BottomNavBar/index.tsx
  src/components/BottomNavBar/style.ts
  src/components/Common/Icons/MainIcon.tsx
  src/components/Common/Icons/NotificationIcon.tsx
  src/components/Common/Icons/ProfileIcon.tsx
  src/components/Common/Icons/ReviewIcon.tsx
  src/pages/MainPage.tsx
Labels: REFACTOR

#96 [✨feat]: 프로필 자기 소개 api연동
  src/hooks/useGetProfile.ts
  src/pages/ProfilePage/index.tsx
  src/services/User/setting.ts
  src/types/payload.ts
  src/types/profile.ts
  src/types/response.ts
Labels: FEAT

#99 [✨feat]: 404 페이지 구현
  public/images/notFoundPageImg.png
  src/components/Common/Button/CTAButton.tsx
  src/pages/NotFoundPage.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/NotFoundPage/style.ts
Labels: FEAT

#105 [🎨style]: 전역 페이지 CSS 스타일링
  src/pages/MainPage/index.tsx
  src/pages/MainPage/style.ts
  src/pages/TestPage.tsx
  src/routes/index.tsx
  src/styles/Theme.ts
  src/styles/emotion.d.ts
Labels: STYLE

#92 [✨feat]: 메인 화면 검색창 및 포스트 검색 페이지 구현
  src/components/Common/EmptySearchResult/index.tsx
  src/components/Common/EmptySearchResult/style.ts
  src/components/PopularSearch/index.tsx
  src/components/PopularSearch/style.ts
  src/components/SearchBar/index.tsx
  src/components/SearchBar/style.ts
  src/components/SearchMap/PlaceList/index.tsx
  src/components/SearchMap/PlaceList/style.ts
  src/components/SearchMap/index.tsx
  src/components/SearchMap/style.ts
  src/pages/MainPage/style.ts
  src/pages/ReviewDetailPage/index.tsx
  src/pages/SearchPostPage/index.tsx
  src/pages/SearchPostPage/style.ts
  src/pages/TestPage.tsx
  src/routes/index.tsx
  src/services/Search/search.ts
  src/types/response.ts
Labels: FEAT

#106 [✨feat]: Spinner 공통 컴포넌트 구현
  package.json
  src/components/Common/Spinner/index.tsx
  src/components/Common/Spinner/style.ts
  src/components/PostUserProfile/index.tsx
  src/main.tsx
  src/pages/MainPage/index.tsx
  yarn.lock
Labels: FEAT

#108 [♻️refactor]: Avatar 컴포넌트 수정
  src/components/Common/Avatar/index.tsx
  src/components/Common/Avatar/style.ts
  src/components/PostUserProfile/index.tsx
  src/constants/avatar.ts
  src/constants/profile.ts
Labels: REFACTOR

#110 [✨feat]: 유저 검색 페이지 구현
  src/components/Common/Icons/PlusMessageIcon.tsx
  src/components/Common/Icons/ProfileFilledIcon.tsx
  src/components/DirectMessage/UserList/index.tsx
  src/components/DirectMessage/UserList/style.ts
  src/components/DirectMessage/UserProfileInfo/index.tsx
  src/components/DirectMessage/UserProfileInfo/style.ts
  src/components/SearchBar/index.tsx
  src/constants/profile.ts
  src/pages/MainPage/style.ts
  src/pages/SearchUserPage/index.tsx
  src/pages/SearchUserPage/style.ts
  src/pages/TestPage.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/Theme.ts
  src/styles/emotion.d.ts
Labels: FEAT

#95 [✨feat]: 페이지 title header 공통 컴포넌트 구현
  src/components/Common/Icons/ChevronLeftIcon.tsx
  src/components/Common/TitleHeader/index.tsx
  src/components/Common/TitleHeader/style.ts
  src/pages/MainPage/index.tsx
  src/routes/path.ts
Labels: FEAT

#114 [✨feat]: 프로필 수정 모달과 File 업로드 로직 연결
  src/components/Common/ImageUpload.tsx
  src/components/Common/Modal/BaseModal/style.ts
  src/components/Common/Modal/ChangeImageModal/index.tsx
  src/components/Common/Modal/ChangeImageModal/style.ts
  src/hooks/useGetProfile.ts
  src/pages/ProfilePage/index.tsx
  src/recoil/selectedFile.ts
  src/utils/file.ts
Labels: FEAT

#115 [✨feat]: '/*'으로 NotFound 경로 추가
  src/routes/index.tsx
  src/routes/path.ts
Labels: FEAT

#116 [✨feat]: 다이렉트 메세지 페이지 구현
  src/components/Common/Icons/CalendarIcon.tsx
  src/components/Common/Icons/SendMessageIcon.tsx
  src/components/DirectMessage/ConversationItem/index.tsx
  src/components/DirectMessage/ConversationItem/style.ts
  src/components/DirectMessage/ConversationList/index.tsx
  src/components/DirectMessage/ConversationList/style.ts
  src/components/DirectMessage/MessageForm/index.tsx
  src/components/DirectMessage/MessageForm/style.ts
  src/components/DirectMessage/MessageItem/index.tsx
  src/components/DirectMessage/MessageItem/style.ts
  src/components/DirectMessage/MessageList/index.tsx
  src/components/DirectMessage/MessageList/style.ts
  src/components/SearchBar/index.tsx
  src/hooks/useConversation.ts
  src/hooks/useNotification.ts
  src/pages/DirectMessagePage/DetailMessagePage/index.tsx
  src/pages/DirectMessagePage/DetailMessagePage/style.ts
  src/pages/DirectMessagePage/index.tsx
  src/pages/DirectMessagePage/style.ts
  src/pages/TestPage.tsx
  src/routes/index.tsx
  src/services/DirectMessage/conversation.ts
  src/services/endPoint.ts
  src/types/payload.ts
  src/types/response.ts
  src/utils/convertTime.ts
Labels: FEAT

#119 [✨feat]: 프로필에서 로그아웃 구현
  src/components/Common/Avatar/index.tsx
  src/components/Common/Button/Button.tsx
  src/components/PostUserProfile/index.tsx
  src/components/PostUserProfile/style.ts
  src/components/UserIntroductionEditor/index.tsx
  src/components/UserIntroductionEditor/style.ts
  src/constants/profile.ts
  src/pages/ProfilePage/index.tsx
  src/pages/ProfilePage/style.ts
Labels: FEAT

#59 [✨feat]: Toast 공통 컴포넌트 구현
  index.html
  src/App.tsx
  src/components/Common/Toast/BaseToast/index.tsx
  src/components/Common/Toast/BaseToast/style.ts
  src/components/Common/Toast/ToastContainer/index.tsx
  src/components/Common/Toast/ToastContainer/style.ts
  src/constants/toast.ts
  src/hooks/useToast.ts
  src/pages/TestPage.tsx
  src/recoil/toast.ts
  src/types/toast.ts
  src/utils/getPositionStyle.ts
Labels: FEAT

#113 [✨feat]: 클릭 시 유저 프로필로 이동하는 hook 구현
  src/components/LikePosts/index.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/hooks/useRedirectProfile.ts
  src/pages/ReviewDetailPage/index.tsx
Labels: FEAT

#122 [♻️refactor]: 하단 NavBar 수정
  src/components/BottomNavBar/index.tsx
  src/components/BottomNavBar/style.ts
  src/components/Common/Icons/MessageIcon.tsx
  src/constants/index.ts
Labels: STYLE, REFACTOR

#126 [♻️refactor]: ReviewCard, ReviewList 수정
  src/components/Channel/ChannelList.tsx
  src/components/Common/DropDown/index.tsx
  src/components/Common/Icons/ThumbsDownIcon.tsx
  src/components/Common/Icons/ThumbsUpIcon.tsx
  src/components/ReviewCard/ReviewCard.tsx
  src/components/ReviewCard/style.ts
  src/components/ReviewCardList/index.tsx
  src/components/ReviewCardList/style.ts
  src/constants/channel.ts
  src/pages/ReviewDetailPage/index.tsx
  src/pages/ReviewDetailPage/style.ts
  src/pages/ReviewList/index.tsx
  src/pages/ReviewList/style.ts
  src/pages/ReviewUpdatePage/index.tsx
  src/services/Post/post.ts
Labels: STYLE, REFACTOR

#127 [✨feat]: react toastify 라이브러리 적용
  package.json
  src/App.tsx
  src/components/Common/Icons/LogoIcon.tsx
  src/components/SignInForm/index.tsx
  src/components/SignUpForm/index.tsx
  src/pages/ProfilePage/index.tsx
  src/pages/ReviewPage/index.tsx
  src/pages/TestPage.tsx
  src/styles/Global.ts
  src/utils/toast.ts
  yarn.lock
Labels: FEAT

#131 [✨feat]: 대화 목록 리스트에 메세지, 마지막으로 보낸 시간 추가
  src/components/DirectMessage/UserProfileInfo/index.tsx
  src/components/DirectMessage/UserProfileInfo/style.ts
Labels: FEAT

#134 [✨feat]: 메인 화면 컴포넌트 교체, 헤더 isBack 설정 변경
  src/components/Common/TitleHeader/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/ReviewList/style.ts
  src/pages/TestPage.tsx
  src/routes/index.tsx
Labels: FEAT

#120 [🐛fix] : 좋아요취소 에러 수정
  src/components/Common/Icons/ClockIcon.tsx
  src/components/ReviewDetail/EvaluationSection.tsx
  src/hooks/ReviewDetail/index.ts
  src/services/Post/like.ts
Labels: FIX

#142 [🐛fix]: SearchPost 데이터 parse 수정, 자기소개 필드 수정
  src/components/PostUserProfile/index.tsx
  src/components/PostUserProfile/style.ts
  src/components/UserIntroductionEditor/index.tsx
  src/components/UserIntroductionEditor/style.ts
  src/pages/ReviewDetailPage/index.tsx
  src/services/Post/post.ts
  src/services/Search/search.ts
Labels: FIX, STYLE

#140 [🐛fix]: 미로그인시 리다이렉트 처리
  src/components/SignInForm/index.tsx
  src/components/SignUpForm/index.tsx
  src/hooks/useAuth.ts
  src/pages/DirectMessagePage/index.tsx
  src/pages/NotificationPage/index.tsx
  src/pages/ProfilePage/index.tsx
  src/pages/ReviewPage/index.tsx
  src/services/axiosInstance.ts
Labels: FIX
